/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ming_youdianmusic_util_JniUtil */

#ifndef _Included_com_example_ming_youdianmusic_util_JniUtil
#define _Included_com_example_ming_youdianmusic_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ming_youdianmusic_util_JniUtil
 * Method:    encryptPassword
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ming_youdianmusic_util_JniUtil_encryptPassword
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
